#############################################################################
# Makefile for building: myfilemanger
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  myfilemanger.pro
# Template: app
# Command: /usr/bin/aqmake -o Makefile myfilemanger.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -march=armv7-a -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -march=armv7-a -march=armv7-a -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Qt-Embedded-5.7.0/include -I/usr/local/Qt-Embedded-5.7.0/include/QtWidgets -I/usr/local/Qt-Embedded-5.7.0/include/QtGui -I/usr/local/Qt-Embedded-5.7.0/include/QtCore -I. -I. -I/usr/local/Qt-Embedded-5.7.0/mkspecs/linux-arm-gnueabi-g++
QMAKE         = /usr/bin/aqmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = myfilemanger1.0.0
DISTDIR = /mnt/hgfs/share/cpp/myfilemanger/.tmp/myfilemanger1.0.0
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Qt-Embedded-5.7.0/lib
LIBS          = $(SUBLIBS) -L/usr/local/Qt-Embedded-5.7.0/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGLESv2 -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-linux-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		myiconprovider.cpp qrc_icon.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		myiconprovider.o \
		qrc_icon.o \
		moc_mainwindow.o
DIST          = icon/Thumbs.db \
		icon/1o.png \
		icon/bmpjpegpng.png \
		icon/bz2zipgz.png \
		icon/c.png \
		icon/cpp.png \
		icon/del.png \
		icon/dir.png \
		icon/doc.png \
		icon/enter.png \
		icon/file.png \
		icon/h.png \
		icon/jpg.png \
		icon/left.png \
		icon/lock.png \
		icon/mp3.png \
		icon/right.png \
		icon/set.png \
		icon/txt.png \
		icon/down.ico \
		icon/left \
		.ico \
		icon/left.ico \
		icon/right.ico \
		icon/up.ico \
		icon/www.easyicon.net.txt \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/unix.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/linux.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/sanitize.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/g++-base.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/qconfig.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/default_post.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/qt.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/resources.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/moc.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/uic.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/file_copies.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/exceptions.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/yacc.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/lex.prf \
		myfilemanger.pro mainwindow.h \
		myiconprovider.h main.cpp \
		mainwindow.cpp \
		myiconprovider.cpp
QMAKE_TARGET  = myfilemanger
DESTDIR       = 
TARGET        = myfilemanger


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: myfilemanger.pro /usr/local/Qt-Embedded-5.7.0/mkspecs/linux-arm-gnueabi-g++/qmake.conf /usr/local/Qt-Embedded-5.7.0/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/unix.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/linux.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/sanitize.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/g++-base.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/qconfig.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/qt_config.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/linux-arm-gnueabi-g++/qmake.conf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/default_pre.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/default_post.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/warn_on.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/qt.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/resources.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/moc.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/uic.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/file_copies.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/exceptions.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/yacc.prf \
		/usr/local/Qt-Embedded-5.7.0/mkspecs/features/lex.prf \
		myfilemanger.pro \
		icon.qrc \
		/usr/local/Qt-Embedded-5.7.0/lib/libQt5Widgets.prl \
		/usr/local/Qt-Embedded-5.7.0/lib/libQt5Gui.prl \
		/usr/local/Qt-Embedded-5.7.0/lib/libQt5Core.prl
	$(QMAKE) -o Makefile myfilemanger.pro
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/spec_pre.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/common/unix.conf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/common/linux.conf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/common/sanitize.conf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/common/gcc-base.conf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/common/g++-base.conf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/common/g++-unix.conf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/qconfig.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_location.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/modules/qt_lib_zlib_private.pri:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/qt_functions.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/qt_config.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/linux-arm-gnueabi-g++/qmake.conf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/default_pre.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/resolve_config.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/default_post.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/warn_on.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/qt.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/resources.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/moc.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/uic.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/unix/thread.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/file_copies.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/exceptions.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/yacc.prf:
/usr/local/Qt-Embedded-5.7.0/mkspecs/features/lex.prf:
myfilemanger.pro:
icon.qrc:
/usr/local/Qt-Embedded-5.7.0/lib/libQt5Widgets.prl:
/usr/local/Qt-Embedded-5.7.0/lib/libQt5Gui.prl:
/usr/local/Qt-Embedded-5.7.0/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile myfilemanger.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents icon.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h myiconprovider.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp myiconprovider.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_icon.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icon.cpp
qrc_icon.cpp: icon.qrc \
		/usr/local/Qt-Embedded-5.7.0/bin/rcc \
		icon/right.ico \
		icon/c.png \
		icon/left.ico \
		icon/bz2zipgz.png \
		icon/h.png \
		icon/enter.png \
		icon/del.png \
		icon/mp3.png \
		icon/bmpjpegpng.png \
		icon/doc.png \
		icon/Thumbs.db \
		icon/txt.png \
		icon/1o.png \
		icon/lock.png \
		icon/set.png \
		icon/file.png \
		icon/cpp.png \
		icon/up.ico \
		icon/www.easyicon.net.txt \
		icon/dir.png \
		icon/right.png \
		icon/down.ico \
		icon/left.png \
		icon/jpg.png
	/usr/local/Qt-Embedded-5.7.0/bin/rcc -name icon icon.qrc -o qrc_icon.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QTableWidgetItem \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtablewidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtableview.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractitemview.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qframe.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qwidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qglobal.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qconfig.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfeatures.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtypetraits.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qisenum.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsysinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlogging.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qflags.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmutex.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qnumeric.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qversiontagging.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qnamespace.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobject.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstring.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qchar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbytearray.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qrefcount.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qarraydata.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qalgorithms.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qiterator.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qpair.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringlist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qregexp.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcoreevent.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmetatype.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobject_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmargins.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qrect.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsize.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qpoint.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpalette.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qcolor.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qrgb.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qrgba64.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qbrush.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvector.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qmatrix.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpolygon.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qregion.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdatastream.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qiodevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qline.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qtransform.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpainterpath.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qimage.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpixelformat.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpixmap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qshareddata.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qhash.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qfont.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qfontinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qcursor.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qkeysequence.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qevent.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvariant.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdebug.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtextstream.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlocale.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qset.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qurl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qurlquery.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfile.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfiledevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qvector2d.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qabstractitemmodel.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qitemselectionmodel.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qstyleoption.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractspinbox.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qvalidator.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qregularexpression.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qicon.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qslider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractslider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qstyle.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtabbar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qrubberband.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QMainWindow \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QString \
		myiconprovider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/QIcon \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QFileIconProvider \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qfileiconprovider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfileinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QFileInfo \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QDebug \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QDir \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdir.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QStringList \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QAction \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qaction.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qactiongroup.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QMenuBar \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qmenubar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qmenu.h \
		mainwindow.h \
		/usr/local/Qt-Embedded-5.7.0/bin/moc
	/usr/local/Qt-Embedded-5.7.0/bin/moc $(DEFINES) -I/usr/local/Qt-Embedded-5.7.0/mkspecs/linux-arm-gnueabi-g++ -I/mnt/hgfs/share/cpp/myfilemanger -I/usr/local/Qt-Embedded-5.7.0/include -I/usr/local/Qt-Embedded-5.7.0/include/QtWidgets -I/usr/local/Qt-Embedded-5.7.0/include/QtGui -I/usr/local/Qt-Embedded-5.7.0/include/QtCore -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/include/c++/5.4.0 -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/include/c++/5.4.0/arm-none-linux-gnueabi -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/include/c++/5.4.0/backward -I/usr/local/arm/5.4.0/usr/lib/gcc/arm-none-linux-gnueabi/5.4.0/include -I/usr/local/arm/5.4.0/usr/lib/gcc/arm-none-linux-gnueabi/5.4.0/include-fixed -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/include -I/usr/local/arm/5.4.0/usr/arm-none-linux-gnueabi/sysroot/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/local/Qt-Embedded-5.7.0/bin/uic
	/usr/local/Qt-Embedded-5.7.0/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QTableWidgetItem \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtablewidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtableview.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractitemview.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qframe.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qwidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qglobal.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qconfig.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfeatures.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtypetraits.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qisenum.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsysinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlogging.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qflags.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmutex.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qnumeric.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qversiontagging.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qnamespace.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobject.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstring.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qchar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbytearray.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qrefcount.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qarraydata.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qalgorithms.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qiterator.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qpair.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringlist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qregexp.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcoreevent.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmetatype.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobject_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmargins.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qrect.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsize.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qpoint.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpalette.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qcolor.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qrgb.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qrgba64.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qbrush.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvector.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qmatrix.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpolygon.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qregion.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdatastream.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qiodevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qline.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qtransform.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpainterpath.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qimage.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpixelformat.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpixmap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qshareddata.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qhash.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qfont.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qfontinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qcursor.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qkeysequence.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qevent.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvariant.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdebug.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtextstream.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlocale.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qset.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qurl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qurlquery.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfile.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfiledevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qvector2d.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qabstractitemmodel.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qitemselectionmodel.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qstyleoption.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractspinbox.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qvalidator.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qregularexpression.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qicon.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qslider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractslider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qstyle.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtabbar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qrubberband.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QMainWindow \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QString \
		myiconprovider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/QIcon \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QFileIconProvider \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qfileiconprovider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfileinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QFileInfo \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QDebug \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QDir \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdir.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QStringList \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QAction \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qaction.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qactiongroup.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QMenuBar \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qmenubar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qmenu.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QApplication \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qapplication.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qeventloop.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qguiapplication.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QTableWidgetItem \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtablewidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtableview.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractitemview.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qframe.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qwidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qglobal.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qconfig.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfeatures.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtypetraits.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qisenum.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsysinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlogging.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qflags.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmutex.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qnumeric.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qversiontagging.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qnamespace.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobject.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstring.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qchar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbytearray.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qrefcount.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qarraydata.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qalgorithms.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qiterator.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qpair.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringlist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qregexp.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcoreevent.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmetatype.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobject_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmargins.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qrect.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsize.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qpoint.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpalette.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qcolor.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qrgb.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qrgba64.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qbrush.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvector.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qmatrix.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpolygon.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qregion.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdatastream.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qiodevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qline.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qtransform.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpainterpath.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qimage.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpixelformat.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpixmap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qshareddata.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qhash.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qfont.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qfontinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qcursor.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qkeysequence.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qevent.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvariant.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdebug.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtextstream.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlocale.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qset.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qurl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qurlquery.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfile.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfiledevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qvector2d.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qabstractitemmodel.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qitemselectionmodel.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qstyleoption.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractspinbox.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qvalidator.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qregularexpression.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qicon.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qslider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qabstractslider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qstyle.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtabbar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qrubberband.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QMainWindow \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QString \
		myiconprovider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/QIcon \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QFileIconProvider \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qfileiconprovider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfileinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QFileInfo \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QDebug \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QDir \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdir.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QStringList \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QAction \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qaction.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qactiongroup.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QMenuBar \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qmenubar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qmenu.h \
		ui_mainwindow.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QVariant \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QApplication \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qapplication.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qeventloop.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qguiapplication.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qinputmethod.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QButtonGroup \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qbuttongroup.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QHeaderView \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qheaderview.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QStatusBar \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qstatusbar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QTableWidget \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QToolBar \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qtoolbar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QWidget \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QDateTime \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdatetime.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QScrollBar \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qscrollbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

myiconprovider.o: myiconprovider.cpp myiconprovider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QString \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstring.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qchar.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qglobal.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qconfig.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfeatures.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtypetraits.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qisenum.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsysinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlogging.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qflags.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmutex.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qnumeric.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qversiontagging.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbytearray.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qrefcount.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qnamespace.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qarraydata.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/QIcon \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qicon.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsize.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qalgorithms.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qiterator.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qhashfunctions.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qpair.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringlist.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qregexp.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpixmap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qrect.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmargins.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qpoint.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qcolor.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qrgb.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qrgba64.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qshareddata.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qhash.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobject.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcoreevent.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmetatype.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qobject_impl.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qimage.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpixelformat.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qtransform.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qmatrix.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpolygon.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvector.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qregion.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdatastream.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qiodevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qline.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtGui/qpainterpath.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/QFileIconProvider \
		/usr/local/Qt-Embedded-5.7.0/include/QtWidgets/qfileiconprovider.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfileinfo.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfile.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qfiledevice.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QFileInfo \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QDebug \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdebug.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qmap.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qtextstream.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qlocale.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qvariant.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qset.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QDir \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/qdir.h \
		/usr/local/Qt-Embedded-5.7.0/include/QtCore/QStringList
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myiconprovider.o myiconprovider.cpp

qrc_icon.o: qrc_icon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icon.o qrc_icon.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

